<?php

return [
    // Comunes a todas las salas
    'max_families' => 10,   // máximo de participantes por sala
    'min_families' => 2,
    'prune_hours' => 2,     // borra la sala si nadie estuvo presente en estas horas
    'reveal_seconds' => 6,   // pausa mostrando el resultado entre rondas

    // ------------------------------------------------------------ Dibuja y Adivina
    'pictionary' => [
        'rounds_per_family' => 2,
        'round_seconds' => 80,
        'reveal_seconds' => 4,   // cuenta regresiva antes de la próxima ronda

        'words' => [
            'perro', 'gato', 'elefante', 'jirafa', 'pingüino', 'tortuga', 'caballo', 'delfín',
            'mariposa', 'araña', 'cocodrilo', 'pulpo', 'canguro', 'búho', 'ballena', 'abeja',
            'pizza', 'helado', 'banana', 'hamburguesa', 'sandía', 'zanahoria', 'huevo frito',
            'torta', 'empanada', 'sushi', 'palomitas', 'chupetín',
            'silla', 'paraguas', 'lámpara', 'reloj', 'llave', 'escoba', 'tijeras', 'martillo',
            'teléfono', 'televisor', 'guitarra', 'bicicleta', 'cepillo de dientes', 'anteojos',
            'sol', 'arcoíris', 'volcán', 'montaña', 'árbol', 'flor', 'estrella', 'nube', 'río',
            'cascada', 'isla', 'cactus',
            'avión', 'barco', 'tren', 'cohete', 'globo aerostático', 'ambulancia', 'submarino',
            'helicóptero', 'patineta',
            'pirata', 'astronauta', 'payaso', 'robot', 'fantasma', 'superhéroe', 'sirena',
            'dragón', 'mago', 'vaquero',
            'fútbol', 'básquet', 'nadar', 'esquiar', 'boxeo', 'ajedrez', 'saltar la cuerda',
            'pescar', 'bailar',
            'castillo', 'faro', 'circo', 'iglú', 'pirámide', 'carpa de camping',
            'corona', 'tesoro', 'semáforo', 'ancla', 'brújula', 'imán', 'esqueleto', 'momia',
            // Animales
            'zorro', 'lobo', 'oso', 'oveja', 'vaca', 'cerdo', 'gallina', 'pato', 'rana', 'serpiente',
            'murciélago', 'ardilla', 'erizo', 'foca', 'rinoceronte', 'hipopótamo', 'camello', 'llama', 'koala', 'panda',
            'flamenco', 'loro', 'tucán', 'cangrejo', 'caracol', 'medusa', 'caballito de mar', 'escarabajo', 'oruga', 'lechuza',
            // Plantas
            'girasol', 'rosa', 'margarita', 'tulipán', 'hongo', 'helecho', 'palmera', 'pino', 'roble', 'bambú',
            'trébol', 'nenúfar', 'bonsái', 'hoja', 'semilla', 'maceta',
            // Otros
            'cometa', 'molino', 'tobogán', 'columpio',
            // --- Tanda extra ---
            // Comida
            'manzana', 'pera', 'uva', 'naranja', 'limón', 'fresa', 'cereza', 'piña', 'coco', 'kiwi',
            'durazno', 'mango', 'palta', 'tomate', 'papa', 'cebolla', 'ajo', 'lechuga', 'brócoli', 'maíz',
            'pepino', 'champiñón', 'pan', 'queso', 'dona', 'panqueque', 'sándwich', 'taco', 'fideos', 'galleta',
            // Animales
            'tigre', 'león', 'mono', 'gorila', 'cebra', 'ciervo', 'conejo', 'ratón', 'hámster', 'tiburón',
            'orca', 'pez', 'calamar', 'langosta', 'camarón', 'mosquito', 'hormiga', 'saltamontes', 'libélula', 'avispa',
            'iguana', 'dinosaurio', 'unicornio', 'pavo', 'cisne', 'águila', 'halcón', 'cuervo', 'colibrí', 'gaviota',
            // Casa y objetos
            'mesa', 'cama', 'sofá', 'espejo', 'escalera', 'cortina', 'almohada', 'ducha', 'bañera', 'inodoro',
            'heladera', 'horno', 'microondas', 'licuadora', 'tostadora', 'sartén', 'olla', 'cuchara', 'tenedor', 'cuchillo',
            'plato', 'vaso', 'taza', 'botella', 'balde', 'regadera', 'manguera', 'pala', 'serrucho', 'destornillador',
            // Juguetes
            'muñeca', 'oso de peluche', 'trompo', 'dado', 'rompecabezas', 'globo', 'pelota', 'yoyó',
            // Transporte
            'auto', 'camión', 'autobús', 'moto', 'tractor', 'grúa', 'canoa', 'velero', 'patines', 'monopatín',
            // Lugares
            'edificio', 'hospital', 'iglesia', 'puente', 'torre', 'estadio', 'granja', 'cine', 'museo', 'biblioteca',
            'restaurante', 'aeropuerto', 'parque',
            // Personas, oficios y fantasía
            'bebé', 'rey', 'reina', 'princesa', 'caballero', 'ninja', 'bombero', 'policía', 'médico', 'chef',
            'cartero', 'buzo', 'piloto', 'científico', 'hada', 'bruja', 'vampiro', 'extraterrestre', 'ogro',
            // Naturaleza y clima
            'luna', 'rayo', 'tornado', 'copo de nieve', 'fogata', 'roca', 'colina', 'lago', 'ola',
        ],
    ],

    // ------------------------------------------------------------ Trivia
    'trivia' => [
        'rounds' => 8,
        'round_seconds' => 22,
        'reveal_seconds' => 5,
        // answer = índice (0..3) de la opción correcta
        'questions' => [
            ['q' => '¿Cuál es el planeta más grande del sistema solar?', 'options' => ['Marte', 'Júpiter', 'Saturno', 'La Tierra'], 'answer' => 1],
            ['q' => '¿En qué continente está Egipto?', 'options' => ['Asia', 'Europa', 'África', 'Oceanía'], 'answer' => 2],
            ['q' => '¿Cuántos lados tiene un hexágono?', 'options' => ['5', '6', '7', '8'], 'answer' => 1],
            ['q' => '¿Quién pintó La Mona Lisa?', 'options' => ['Picasso', 'Van Gogh', 'Da Vinci', 'Dalí'], 'answer' => 2],
            ['q' => '¿Cuál es el animal terrestre más rápido?', 'options' => ['León', 'Guepardo', 'Caballo', 'Galgo'], 'answer' => 1],
            ['q' => '¿En qué país se inventó la pizza?', 'options' => ['Francia', 'España', 'Italia', 'Grecia'], 'answer' => 2],
            ['q' => '¿Cuántos huesos tiene el cuerpo humano adulto?', 'options' => ['206', '150', '300', '250'], 'answer' => 0],
            ['q' => '¿Cuál es el océano más grande?', 'options' => ['Atlántico', 'Índico', 'Ártico', 'Pacífico'], 'answer' => 3],
            ['q' => '¿Qué gas respiramos para vivir?', 'options' => ['Hidrógeno', 'Oxígeno', 'Nitrógeno', 'Helio'], 'answer' => 1],
            ['q' => '¿Cuántos jugadores tiene un equipo de fútbol en cancha?', 'options' => ['9', '10', '11', '12'], 'answer' => 2],
            ['q' => '¿Cuál es la capital de Japón?', 'options' => ['Pekín', 'Seúl', 'Tokio', 'Bangkok'], 'answer' => 2],
            ['q' => '¿De qué color es la clorofila?', 'options' => ['Roja', 'Verde', 'Azul', 'Amarilla'], 'answer' => 1],
            ['q' => '¿Cuál es el metal líquido a temperatura ambiente?', 'options' => ['Hierro', 'Mercurio', 'Oro', 'Plomo'], 'answer' => 1],
            ['q' => '¿Cuántos colores tiene el arcoíris?', 'options' => ['5', '6', '7', '8'], 'answer' => 2],
            ['q' => '¿Qué instrumento tiene 88 teclas?', 'options' => ['Guitarra', 'Piano', 'Violín', 'Arpa'], 'answer' => 1],
            ['q' => '¿En qué país están las pirámides de Giza?', 'options' => ['México', 'Egipto', 'Perú', 'Irak'], 'answer' => 1],
            ['q' => '¿Cuál es el río más largo del mundo?', 'options' => ['Nilo', 'Amazonas', 'Misisipi', 'Yangtsé'], 'answer' => 1],
            ['q' => '¿Cuántas patas tiene una araña?', 'options' => ['6', '8', '10', '12'], 'answer' => 1],
            ['q' => '¿Qué planeta es conocido como el planeta rojo?', 'options' => ['Venus', 'Marte', 'Mercurio', 'Neptuno'], 'answer' => 1],
            ['q' => '¿Cuál es la moneda de Estados Unidos?', 'options' => ['Euro', 'Peso', 'Dólar', 'Libra'], 'answer' => 2],
            ['q' => '¿Cuántas patas tiene un insecto?', 'options' => ['4', '6', '8', '10'], 'answer' => 1],
            ['q' => '¿Qué animal es el rey de la selva?', 'options' => ['Tigre', 'León', 'Elefante', 'Oso'], 'answer' => 1],
            ['q' => '¿Cuál es el planeta más cercano al Sol?', 'options' => ['Venus', 'Mercurio', 'Marte', 'La Tierra'], 'answer' => 1],
            ['q' => '¿De qué animal obtenemos la lana?', 'options' => ['Vaca', 'Oveja', 'Cerdo', 'Caballo'], 'answer' => 1],
            ['q' => '¿Cuántos días tiene una semana?', 'options' => ['5', '6', '7', '8'], 'answer' => 2],
            ['q' => '¿Qué fruta es amarilla y curva?', 'options' => ['Manzana', 'Banana', 'Uva', 'Pera'], 'answer' => 1],
            ['q' => '¿Cuál es el idioma más hablado en Brasil?', 'options' => ['Español', 'Portugués', 'Inglés', 'Francés'], 'answer' => 1],
            ['q' => '¿Cuántos minutos tiene una hora?', 'options' => ['30', '45', '60', '90'], 'answer' => 2],
            ['q' => '¿Qué usan los médicos para escuchar el corazón?', 'options' => ['Termómetro', 'Estetoscopio', 'Jeringa', 'Lupa'], 'answer' => 1],
            ['q' => '¿Cuál es el continente más grande?', 'options' => ['África', 'Asia', 'América', 'Europa'], 'answer' => 1],
            ['q' => '¿A qué temperatura se congela el agua?', 'options' => ['0°C', '50°C', '100°C', '-50°C'], 'answer' => 0],
            ['q' => '¿Cuál de estos es un mamífero marino?', 'options' => ['Tiburón', 'Delfín', 'Pulpo', 'Cangrejo'], 'answer' => 1],
            ['q' => '¿De qué color es el sol de la bandera de Argentina?', 'options' => ['Blanco', 'Amarillo', 'Rojo', 'Azul'], 'answer' => 1],
            ['q' => '¿Cuántas ruedas tiene una bicicleta?', 'options' => ['1', '2', '3', '4'], 'answer' => 1],
            ['q' => '¿Qué órgano bombea la sangre?', 'options' => ['Pulmón', 'Corazón', 'Hígado', 'Riñón'], 'answer' => 1],
            ['q' => '¿En qué estación hace más calor?', 'options' => ['Invierno', 'Verano', 'Otoño', 'Primavera'], 'answer' => 1],
            ['q' => '¿Cuántos lados tiene un triángulo?', 'options' => ['2', '3', '4', '5'], 'answer' => 1],
            ['q' => '¿Qué planeta tiene anillos famosos?', 'options' => ['Marte', 'Saturno', 'Venus', 'Júpiter'], 'answer' => 1],
            ['q' => '¿Cuál es la capital de Francia?', 'options' => ['Roma', 'Madrid', 'París', 'Berlín'], 'answer' => 2],
            ['q' => '¿Qué se usa para escribir en el pizarrón?', 'options' => ['Tiza', 'Martillo', 'Cuchara', 'Peine'], 'answer' => 0],
            ['q' => '¿Cuántos dedos tiene una mano?', 'options' => ['4', '5', '6', '10'], 'answer' => 1],
            ['q' => '¿Qué animal tiene trompa y es muy grande?', 'options' => ['Jirafa', 'Elefante', 'Rinoceronte', 'Camello'], 'answer' => 1],
            ['q' => '¿Cuál es la capital de Italia?', 'options' => ['Milán', 'Nápoles', 'Roma', 'Turín'], 'answer' => 2],
            ['q' => '¿Qué producen las abejas?', 'options' => ['Leche', 'Miel', 'Seda', 'Lana'], 'answer' => 1],
            ['q' => '¿Cuántos planetas tiene el sistema solar?', 'options' => ['7', '8', '9', '10'], 'answer' => 1],
            ['q' => '¿Qué animal cambia de color para camuflarse?', 'options' => ['Camaleón', 'Perro', 'Caballo', 'Vaca'], 'answer' => 0],
            ['q' => '¿Cuál es el metal precioso de color amarillo?', 'options' => ['Plata', 'Oro', 'Cobre', 'Hierro'], 'answer' => 1],
            ['q' => '¿Qué usamos para ver las estrellas de cerca?', 'options' => ['Microscopio', 'Telescopio', 'Lupa', 'Espejo'], 'answer' => 1],
            ['q' => '¿Cuál es la capital de España?', 'options' => ['Barcelona', 'Madrid', 'Sevilla', 'Valencia'], 'answer' => 1],
            ['q' => '¿Cuántos meses tiene un año?', 'options' => ['10', '11', '12', '13'], 'answer' => 2],
            ['q' => '¿Qué necesita una planta para crecer, además de agua?', 'options' => ['Oscuridad', 'Luz solar', 'Sal', 'Aceite'], 'answer' => 1],
            ['q' => '¿Qué ave no vuela y vive en la Antártida?', 'options' => ['Águila', 'Pingüino', 'Loro', 'Gaviota'], 'answer' => 1],
            ['q' => '¿Qué forma tiene una pelota?', 'options' => ['Cuadrada', 'Esfera', 'Triángulo', 'Cubo'], 'answer' => 1],
            ['q' => '¿Cuál es el río más largo de Sudamérica?', 'options' => ['Paraná', 'Amazonas', 'Orinoco', 'Magdalena'], 'answer' => 1],
            ['q' => '¿Cuántas cuerdas tiene una guitarra clásica?', 'options' => ['4', '5', '6', '7'], 'answer' => 2],
            ['q' => '¿En qué planeta vivimos?', 'options' => ['Marte', 'La Tierra', 'La Luna', 'Venus'], 'answer' => 1],
            ['q' => '¿Cuál es la capital de México?', 'options' => ['Guadalajara', 'Cancún', 'Ciudad de México', 'Monterrey'], 'answer' => 2],
            ['q' => '¿Qué usamos para protegernos de la lluvia?', 'options' => ['Paraguas', 'Abanico', 'Linterna', 'Reloj'], 'answer' => 0],
            ['q' => '¿Cuál es el animal más alto del mundo?', 'options' => ['Elefante', 'Jirafa', 'Caballo', 'Camello'], 'answer' => 1],
            ['q' => '¿Qué color se forma al mezclar azul y amarillo?', 'options' => ['Verde', 'Naranja', 'Violeta', 'Marrón'], 'answer' => 0],
            ['q' => '¿Qué deporte se juega con raqueta y una pelota amarilla?', 'options' => ['Fútbol', 'Tenis', 'Básquet', 'Golf'], 'answer' => 1],
            ['q' => '¿Cuál es la estrella más cercana a la Tierra?', 'options' => ['La Luna', 'El Sol', 'Marte', 'Sirio'], 'answer' => 1],
            ['q' => '¿Qué animal ronronea?', 'options' => ['Perro', 'Gato', 'Vaca', 'Pato'], 'answer' => 1],
            ['q' => '¿Cuál es la capital de Estados Unidos?', 'options' => ['Nueva York', 'Washington D.C.', 'Los Ángeles', 'Chicago'], 'answer' => 1],
            ['q' => '¿Qué comen principalmente los conejos?', 'options' => ['Carne', 'Zanahorias', 'Pescado', 'Insectos'], 'answer' => 1],
            ['q' => '¿Cuántas letras tiene el abecedario español (aprox.)?', 'options' => ['21', '27', '30', '33'], 'answer' => 1],
            ['q' => '¿Cuál es el ave nacional que corre muy rápido y no vuela?', 'options' => ['Avestruz', 'Cóndor', 'Colibrí', 'Búho'], 'answer' => 0],
            ['q' => '¿Qué planeta es famoso por ser rojo?', 'options' => ['Júpiter', 'Marte', 'Saturno', 'Neptuno'], 'answer' => 1],
            ['q' => '¿Cuánto es 7 x 8?', 'options' => ['54', '56', '63', '48'], 'answer' => 1],
            ['q' => '¿Qué instrumento tiene teclas blancas y negras?', 'options' => ['Violín', 'Piano', 'Flauta', 'Batería'], 'answer' => 1],
            ['q' => '¿Cuál es el hueso más largo del cuerpo?', 'options' => ['Fémur', 'Cráneo', 'Costilla', 'Columna'], 'answer' => 0],
            // --- Tanda extra ---
            ['q' => '¿Cuál es la capital de Argentina?', 'options' => ['Córdoba', 'Buenos Aires', 'Rosario', 'Mendoza'], 'answer' => 1],
            ['q' => '¿Cuál es la capital de Perú?', 'options' => ['Lima', 'Quito', 'La Paz', 'Bogotá'], 'answer' => 0],
            ['q' => '¿Cuál es la capital de Chile?', 'options' => ['Valparaíso', 'Santiago', 'Concepción', 'Antofagasta'], 'answer' => 1],
            ['q' => '¿Cuál es la capital de Colombia?', 'options' => ['Medellín', 'Cali', 'Bogotá', 'Cartagena'], 'answer' => 2],
            ['q' => '¿Cuál es la capital de Alemania?', 'options' => ['Múnich', 'Berlín', 'Hamburgo', 'Frankfurt'], 'answer' => 1],
            ['q' => '¿Cuál es la capital del Reino Unido?', 'options' => ['Londres', 'Mánchester', 'Liverpool', 'Oxford'], 'answer' => 0],
            ['q' => '¿Cuál es la capital de Portugal?', 'options' => ['Oporto', 'Lisboa', 'Braga', 'Faro'], 'answer' => 1],
            ['q' => '¿Cuál es la capital de Rusia?', 'options' => ['San Petersburgo', 'Moscú', 'Kiev', 'Minsk'], 'answer' => 1],
            ['q' => '¿Cuál es la capital de China?', 'options' => ['Shanghái', 'Pekín', 'Hong Kong', 'Cantón'], 'answer' => 1],
            ['q' => '¿Cuál es la capital de Canadá?', 'options' => ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'], 'answer' => 1],
            ['q' => '¿Qué país tiene forma de bota?', 'options' => ['España', 'Italia', 'Grecia', 'Portugal'], 'answer' => 1],
            ['q' => '¿De qué país son típicos los canguros?', 'options' => ['Australia', 'India', 'Egipto', 'México'], 'answer' => 0],
            ['q' => '¿Qué océano separa América de Europa?', 'options' => ['Pacífico', 'Atlántico', 'Índico', 'Ártico'], 'answer' => 1],
            ['q' => '¿Cuál es el desierto más grande y caluroso de África?', 'options' => ['Gobi', 'Sahara', 'Atacama', 'Kalahari'], 'answer' => 1],
            ['q' => '¿Cómo se llaman las cataratas entre Argentina y Brasil?', 'options' => ['Niágara', 'Iguazú', 'Victoria', 'Ángel'], 'answer' => 1],
            ['q' => '¿Cuál es la montaña más alta del mundo?', 'options' => ['Aconcagua', 'Everest', 'Kilimanjaro', 'Mont Blanc'], 'answer' => 1],
            ['q' => '¿Cuál es el país más grande del mundo?', 'options' => ['Canadá', 'China', 'Rusia', 'Estados Unidos'], 'answer' => 2],
            ['q' => '¿Cuál es la moneda de Japón?', 'options' => ['Won', 'Yen', 'Yuan', 'Rupia'], 'answer' => 1],
            ['q' => '¿En qué país está la Torre Eiffel?', 'options' => ['Italia', 'Francia', 'España', 'Inglaterra'], 'answer' => 1],
            ['q' => '¿En qué país está la Estatua de la Libertad?', 'options' => ['Francia', 'Estados Unidos', 'Canadá', 'México'], 'answer' => 1],
            ['q' => '¿En qué país está el Coliseo?', 'options' => ['Grecia', 'Italia', 'España', 'Egipto'], 'answer' => 1],
            ['q' => '¿En qué país está la Muralla China?', 'options' => ['Japón', 'China', 'India', 'Corea'], 'answer' => 1],
            ['q' => '¿De qué colores es principalmente la bandera de Brasil?', 'options' => ['Rojo y blanco', 'Verde y amarillo', 'Azul y blanco', 'Negro y rojo'], 'answer' => 1],
            ['q' => '¿Cuántas lunas tiene la Tierra?', 'options' => ['1', '2', '3', '0'], 'answer' => 0],
            ['q' => '¿Qué gas usan las plantas para la fotosíntesis?', 'options' => ['Oxígeno', 'Dióxido de carbono', 'Helio', 'Nitrógeno'], 'answer' => 1],
            ['q' => '¿Qué fuerza nos mantiene pegados al suelo?', 'options' => ['Magnetismo', 'Gravedad', 'Fricción', 'Electricidad'], 'answer' => 1],
            ['q' => '¿En qué estado está el agua cuando hierve?', 'options' => ['Sólido', 'Líquido', 'Gas', 'Plasma'], 'answer' => 2],
            ['q' => '¿De qué están hechas las nubes?', 'options' => ['Humo', 'Gotas de agua', 'Algodón', 'Polvo'], 'answer' => 1],
            ['q' => '¿Qué parte de la planta absorbe el agua?', 'options' => ['Hoja', 'Raíz', 'Flor', 'Fruto'], 'answer' => 1],
            ['q' => '¿Qué atrae un imán?', 'options' => ['Madera', 'Hierro', 'Plástico', 'Vidrio'], 'answer' => 1],
            ['q' => '¿Cuál es el animal más grande del mundo?', 'options' => ['Elefante', 'Ballena azul', 'Tiburón', 'Jirafa'], 'answer' => 1],
            ['q' => '¿Cuántos corazones tiene un pulpo?', 'options' => ['1', '2', '3', '5'], 'answer' => 2],
            ['q' => '¿Qué mamífero pone huevos?', 'options' => ['Canguro', 'Ornitorrinco', 'Delfín', 'Murciélago'], 'answer' => 1],
            ['q' => '¿Cuántas alas tiene una mariposa?', 'options' => ['2', '4', '6', '8'], 'answer' => 1],
            ['q' => '¿Qué come principalmente el oso panda?', 'options' => ['Carne', 'Bambú', 'Pescado', 'Miel'], 'answer' => 1],
            ['q' => '¿Dónde vive el oso polar?', 'options' => ['Desierto', 'Ártico', 'Selva', 'Sabana'], 'answer' => 1],
            ['q' => '¿Qué reptil tiene caparazón?', 'options' => ['Serpiente', 'Tortuga', 'Lagarto', 'Cocodrilo'], 'answer' => 1],
            ['q' => '¿Qué ave puede imitar la voz humana?', 'options' => ['Gallina', 'Loro', 'Pato', 'Cisne'], 'answer' => 1],
            ['q' => '¿Qué animal duerme colgado boca abajo?', 'options' => ['Búho', 'Murciélago', 'Ardilla', 'Gato'], 'answer' => 1],
            ['q' => '¿Qué animal tiene un cuello muy largo?', 'options' => ['Elefante', 'Jirafa', 'Camello', 'Avestruz'], 'answer' => 1],
            ['q' => '¿Qué animal tiene rayas blancas y negras?', 'options' => ['Tigre', 'Cebra', 'Panda', 'Vaca'], 'answer' => 1],
            ['q' => '¿Qué animal construye represas en los ríos?', 'options' => ['Nutria', 'Castor', 'Rana', 'Pato'], 'answer' => 1],
            ['q' => '¿Qué ave es símbolo de la paz?', 'options' => ['Águila', 'Paloma', 'Cuervo', 'Loro'], 'answer' => 1],
            ['q' => '¿Qué animal produce seda?', 'options' => ['Araña', 'Gusano de seda', 'Abeja', 'Oruga'], 'answer' => 1],
            ['q' => '¿Cuántos jugadores tiene un equipo de vóley en cancha?', 'options' => ['5', '6', '7', '11'], 'answer' => 1],
            ['q' => '¿Cada cuántos años se hacen los Juegos Olímpicos?', 'options' => ['2', '3', '4', '5'], 'answer' => 2],
            ['q' => '¿En qué deporte hay un "home run"?', 'options' => ['Fútbol', 'Béisbol', 'Tenis', 'Golf'], 'answer' => 1],
            ['q' => '¿Cuántos anillos tiene la bandera olímpica?', 'options' => ['3', '4', '5', '6'], 'answer' => 2],
            ['q' => '¿En qué país nacieron los Juegos Olímpicos antiguos?', 'options' => ['Italia', 'Grecia', 'Egipto', 'China'], 'answer' => 1],
            ['q' => '¿Cuánto es 9 x 9?', 'options' => ['72', '81', '90', '99'], 'answer' => 1],
            ['q' => '¿Cuánto es 100 dividido 4?', 'options' => ['20', '25', '40', '50'], 'answer' => 1],
            ['q' => '¿Cuántos lados tiene un cuadrado?', 'options' => ['3', '4', '5', '6'], 'answer' => 1],
            ['q' => '¿Cuánto es 12 + 15?', 'options' => ['25', '26', '27', '28'], 'answer' => 2],
            ['q' => '¿Cuántos minutos hay en media hora?', 'options' => ['15', '20', '30', '45'], 'answer' => 2],
            ['q' => '¿Qué número sigue: 2, 4, 6, 8, ...?', 'options' => ['9', '10', '11', '12'], 'answer' => 1],
            ['q' => '¿Cuánto es la mitad de 50?', 'options' => ['20', '25', '30', '100'], 'answer' => 1],
            ['q' => '¿Cuántos lados tiene un pentágono?', 'options' => ['4', '5', '6', '7'], 'answer' => 1],
            ['q' => '¿Cuánto es 6 x 7?', 'options' => ['36', '42', '48', '49'], 'answer' => 1],
            ['q' => '¿Cuánto es una docena?', 'options' => ['6', '10', '12', '20'], 'answer' => 2],
            ['q' => '¿Con qué órgano respiramos?', 'options' => ['Corazón', 'Pulmones', 'Hígado', 'Estómago'], 'answer' => 1],
            ['q' => '¿Qué órgano controla el pensamiento?', 'options' => ['Corazón', 'Cerebro', 'Pulmón', 'Hígado'], 'answer' => 1],
            ['q' => '¿Con qué sentido olemos?', 'options' => ['Vista', 'Olfato', 'Tacto', 'Oído'], 'answer' => 1],
            ['q' => '¿Qué recubre y protege todo el cuerpo?', 'options' => ['El pelo', 'La piel', 'Los huesos', 'La sangre'], 'answer' => 1],
            ['q' => '¿Con qué parte del cuerpo escuchamos?', 'options' => ['Ojos', 'Oídos', 'Nariz', 'Boca'], 'answer' => 1],
            ['q' => '¿Qué bebida es fundamental para vivir?', 'options' => ['Gaseosa', 'Agua', 'Jugo', 'Café'], 'answer' => 1],
            ['q' => '¿Quién llegó a América en 1492?', 'options' => ['Napoleón', 'Cristóbal Colón', 'Einstein', 'Edison'], 'answer' => 1],
            ['q' => '¿Qué construían los egipcios como grandes tumbas?', 'options' => ['Castillos', 'Pirámides', 'Rascacielos', 'Puentes'], 'answer' => 1],
            ['q' => '¿Quién pintó "La noche estrellada"?', 'options' => ['Picasso', 'Van Gogh', 'Da Vinci', 'Monet'], 'answer' => 1],
            ['q' => '¿Qué inventó Thomas Edison?', 'options' => ['El teléfono', 'La bombilla', 'El auto', 'La radio'], 'answer' => 1],
            ['q' => '¿Cómo se llama nuestra galaxia?', 'options' => ['Andrómeda', 'Vía Láctea', 'Orión', 'Sirio'], 'answer' => 1],
            ['q' => '¿Quién fue el primer hombre en pisar la Luna?', 'options' => ['Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'Elon Musk'], 'answer' => 1],
            ['q' => '¿Cuál es el planeta más cercano a la Tierra?', 'options' => ['Marte', 'Venus', 'Júpiter', 'Mercurio'], 'answer' => 1],
            ['q' => '¿Qué es en realidad una estrella fugaz?', 'options' => ['Un planeta', 'Un meteoro', 'Un satélite', 'Una galaxia'], 'answer' => 1],
            ['q' => '¿Cuál es el planeta más pequeño del sistema solar?', 'options' => ['Marte', 'Mercurio', 'Venus', 'Neptuno'], 'answer' => 1],
            ['q' => '¿Qué necesitan los peces para respirar bajo el agua?', 'options' => ['Pulmones', 'Branquias', 'Nariz', 'Aletas'], 'answer' => 1],
            ['q' => '¿Qué expulsa un volcán al hacer erupción?', 'options' => ['Agua', 'Lava', 'Nieve', 'Arena'], 'answer' => 1],
            ['q' => '¿Qué se forma cuando el agua se enfría mucho?', 'options' => ['Vapor', 'Hielo', 'Niebla', 'Sal'], 'answer' => 1],
            ['q' => '¿Qué aparece en el cielo tras la lluvia con sol?', 'options' => ['Rayo', 'Arcoíris', 'Niebla', 'Nieve'], 'answer' => 1],
            ['q' => '¿Qué instrumento indica el norte?', 'options' => ['Reloj', 'Brújula', 'Termómetro', 'Regla'], 'answer' => 1],
            ['q' => '¿Qué estación viene después del invierno?', 'options' => ['Verano', 'Primavera', 'Otoño', 'Invierno'], 'answer' => 1],
            ['q' => '¿Cuántas estaciones del año hay?', 'options' => ['2', '3', '4', '5'], 'answer' => 2],
            ['q' => '¿Qué astro ilumina la noche?', 'options' => ['El Sol', 'La Luna', 'Marte', 'Un cometa'], 'answer' => 1],
            ['q' => '¿Qué máquina lava la ropa?', 'options' => ['Heladera', 'Lavarropas', 'Horno', 'Licuadora'], 'answer' => 1],
            ['q' => '¿Dónde guardamos la comida para que no se eche a perder?', 'options' => ['Horno', 'Heladera', 'Armario', 'Cajón'], 'answer' => 1],
            ['q' => '¿Qué color se forma al mezclar rojo y amarillo?', 'options' => ['Verde', 'Naranja', 'Violeta', 'Marrón'], 'answer' => 1],
            ['q' => '¿Qué color se forma al mezclar rojo y azul?', 'options' => ['Verde', 'Naranja', 'Violeta', 'Rosa'], 'answer' => 2],
            ['q' => '¿Cuántos colores primarios hay?', 'options' => ['2', '3', '4', '5'], 'answer' => 1],
            ['q' => '¿Cuántas cuerdas tiene un violín?', 'options' => ['3', '4', '5', '6'], 'answer' => 1],
            ['q' => '¿Qué instrumento se toca con baquetas?', 'options' => ['Guitarra', 'Batería', 'Violín', 'Flauta'], 'answer' => 1],
            ['q' => '¿Qué instrumento tiene cuerdas y se rasguea?', 'options' => ['Piano', 'Guitarra', 'Trompeta', 'Tambor'], 'answer' => 1],
            ['q' => '¿De qué fruta se hace el vino?', 'options' => ['Manzana', 'Uva', 'Naranja', 'Pera'], 'answer' => 1],
            ['q' => '¿De qué animal viene la mayoría de la leche que tomamos?', 'options' => ['Gallina', 'Vaca', 'Oveja', 'Caballo'], 'answer' => 1],
            ['q' => '¿Qué fruta amarilla es muy agria?', 'options' => ['Banana', 'Limón', 'Naranja', 'Melón'], 'answer' => 1],
            ['q' => '¿Qué se obtiene de las aceitunas?', 'options' => ['Manteca', 'Aceite de oliva', 'Vinagre', 'Miel'], 'answer' => 1],
            ['q' => '¿De qué cereal se hace normalmente el pan?', 'options' => ['Arroz', 'Trigo', 'Maíz', 'Avena'], 'answer' => 1],
            ['q' => '¿De qué árbol caen las bellotas?', 'options' => ['Pino', 'Roble', 'Palmera', 'Sauce'], 'answer' => 1],
            ['q' => '¿Qué insecto poliniza las flores?', 'options' => ['Mosca', 'Abeja', 'Araña', 'Hormiga'], 'answer' => 1],
            ['q' => '¿De qué color es el cielo despejado de día?', 'options' => ['Verde', 'Azul', 'Rojo', 'Gris'], 'answer' => 1],
            ['q' => '¿Cuántas ruedas tiene un auto común?', 'options' => ['2', '3', '4', '6'], 'answer' => 2],
            ['q' => '¿Qué usamos para cortar papel?', 'options' => ['Martillo', 'Tijera', 'Cuchara', 'Regla'], 'answer' => 1],
            ['q' => '¿Qué día viene después del lunes?', 'options' => ['Domingo', 'Martes', 'Miércoles', 'Viernes'], 'answer' => 1],
            ['q' => '¿Cuántos días tiene febrero en un año común?', 'options' => ['28', '29', '30', '31'], 'answer' => 0],
            ['q' => '¿Con qué mes empieza el año?', 'options' => ['Diciembre', 'Enero', 'Marzo', 'Junio'], 'answer' => 1],
            ['q' => '¿Qué figura no tiene lados ni esquinas?', 'options' => ['Círculo', 'Cuadrado', 'Triángulo', 'Rectángulo'], 'answer' => 0],
            ['q' => '¿Qué usamos para saber la hora?', 'options' => ['Termómetro', 'Reloj', 'Brújula', 'Regla'], 'answer' => 1],
            ['q' => '¿Qué transporte vuela y tiene alas?', 'options' => ['Barco', 'Avión', 'Tren', 'Auto'], 'answer' => 1],
            ['q' => '¿Qué transporte anda sobre rieles?', 'options' => ['Auto', 'Tren', 'Barco', 'Avión'], 'answer' => 1],
            ['q' => '¿Qué vehículo apaga incendios?', 'options' => ['Ambulancia', 'Camión de bomberos', 'Patrullero', 'Taxi'], 'answer' => 1],
            ['q' => '¿Qué usamos en los ojos para protegernos del sol?', 'options' => ['Bufanda', 'Anteojos de sol', 'Guantes', 'Gorro'], 'answer' => 1],
            ['q' => '¿Qué animal es un gran nadador?', 'options' => ['Gato', 'Delfín', 'Caballo', 'Conejo'], 'answer' => 1],
            ['q' => '¿Cuál es el ave más grande y que no vuela?', 'options' => ['Avestruz', 'Águila', 'Cóndor', 'Flamenco'], 'answer' => 0],
            ['q' => '¿Qué usamos para escribir en un cuaderno?', 'options' => ['Pincel', 'Lápiz', 'Tiza', 'Martillo'], 'answer' => 1],
            ['q' => '¿Qué animal es el rey de la sabana y ruge fuerte?', 'options' => ['Tigre', 'León', 'Oso', 'Lobo'], 'answer' => 1],
            ['q' => '¿Qué figura tiene exactamente 3 lados?', 'options' => ['Círculo', 'Triángulo', 'Cuadrado', 'Rombo'], 'answer' => 1],
            ['q' => '¿Cuál es la capital de Uruguay?', 'options' => ['Punta del Este', 'Montevideo', 'Salto', 'Colonia'], 'answer' => 1],
            ['q' => '¿Cuál es la capital de Ecuador?', 'options' => ['Guayaquil', 'Quito', 'Cuenca', 'Loja'], 'answer' => 1],
            ['q' => '¿Cuál es el río más caudaloso del mundo?', 'options' => ['Nilo', 'Amazonas', 'Danubio', 'Misisipi'], 'answer' => 1],
            ['q' => '¿En qué continente está Egipto?', 'options' => ['Asia', 'África', 'Europa', 'Oceanía'], 'answer' => 1],
            ['q' => '¿Qué instrumento mide la temperatura del cuerpo?', 'options' => ['Barómetro', 'Termómetro', 'Reloj', 'Brújula'], 'answer' => 1],
            ['q' => '¿Qué animal cambia de piel (muda)?', 'options' => ['Perro', 'Serpiente', 'Gato', 'Caballo'], 'answer' => 1],
            ['q' => '¿Cuánto es 8 + 7?', 'options' => ['13', '14', '15', '16'], 'answer' => 2],
            ['q' => '¿Cuánto es 5 x 6?', 'options' => ['25', '30', '35', '11'], 'answer' => 1],
            ['q' => '¿Qué se necesita para que crezca fuego?', 'options' => ['Agua', 'Oxígeno', 'Hielo', 'Arena'], 'answer' => 1],
            ['q' => '¿Qué planeta está justo después de la Tierra (alejándose del Sol)?', 'options' => ['Venus', 'Marte', 'Mercurio', 'Saturno'], 'answer' => 1],
            ['q' => '¿Qué animal tiene una joroba (o dos) y vive en el desierto?', 'options' => ['Caballo', 'Camello', 'Llama', 'Burro'], 'answer' => 1],
            ['q' => '¿Qué color se obtiene al mezclar todos los colores de la luz?', 'options' => ['Negro', 'Blanco', 'Gris', 'Marrón'], 'answer' => 1],
            ['q' => '¿Qué usamos para ver cosas muy pequeñas de cerca?', 'options' => ['Telescopio', 'Microscopio', 'Binoculares', 'Espejo'], 'answer' => 1],
            ['q' => '¿Cuántos segundos tiene un minuto?', 'options' => ['30', '60', '90', '100'], 'answer' => 1],
            ['q' => '¿Qué parte del cuerpo usamos para pensar y recordar?', 'options' => ['El estómago', 'El cerebro', 'El corazón', 'La mano'], 'answer' => 1],
            ['q' => '¿Cuál es la fruta nacional… digo, la fruta del árbol de manzano?', 'options' => ['Pera', 'Manzana', 'Durazno', 'Ciruela'], 'answer' => 1],
            ['q' => '¿Qué animal ladra?', 'options' => ['Gato', 'Perro', 'Vaca', 'Caballo'], 'answer' => 1],
            ['q' => '¿Qué animal maúlla?', 'options' => ['Perro', 'Gato', 'Pato', 'Oveja'], 'answer' => 1],
            ['q' => '¿Qué animal relincha?', 'options' => ['Vaca', 'Caballo', 'Cerdo', 'Gallina'], 'answer' => 1],
            ['q' => '¿Cuántas patas tiene una silla común?', 'options' => ['2', '3', '4', '5'], 'answer' => 2],
            ['q' => '¿Qué hace un termómetro?', 'options' => ['Mide el tiempo', 'Mide la temperatura', 'Mide la distancia', 'Mide el peso'], 'answer' => 1],
            ['q' => '¿Qué se usa para pesar cosas?', 'options' => ['Balanza', 'Regla', 'Reloj', 'Brújula'], 'answer' => 0],
            ['q' => '¿Cuál es la capital de España?', 'options' => ['Barcelona', 'Madrid', 'Sevilla', 'Bilbao'], 'answer' => 1],
            ['q' => '¿Qué animal vive en colmenas y hace zumbido?', 'options' => ['Mosca', 'Abeja', 'Mariposa', 'Araña'], 'answer' => 1],
            ['q' => '¿Qué se forma al mezclar amarillo y azul?', 'options' => ['Verde', 'Naranja', 'Violeta', 'Rojo'], 'answer' => 0],
            ['q' => '¿Cuántas patas tiene un caballo?', 'options' => ['2', '4', '6', '8'], 'answer' => 1],
            ['q' => '¿Qué se pone en la cabeza un rey?', 'options' => ['Bufanda', 'Corona', 'Sombrero de paja', 'Casco'], 'answer' => 1],
            ['q' => '¿Qué animal es famoso por ser muy lento?', 'options' => ['Guepardo', 'Tortuga', 'Liebre', 'Caballo'], 'answer' => 1],
            ['q' => '¿Qué usás para peinarte?', 'options' => ['Peine', 'Tenedor', 'Cuchara', 'Pincel'], 'answer' => 0],
            ['q' => '¿Qué órgano late en el pecho?', 'options' => ['Pulmón', 'Corazón', 'Cerebro', 'Riñón'], 'answer' => 1],
            ['q' => '¿Qué debemos hacer antes de comer?', 'options' => ['Correr', 'Lavarnos las manos', 'Saltar', 'Gritar'], 'answer' => 1],
            ['q' => '¿Qué transporte navega en el agua?', 'options' => ['Avión', 'Barco', 'Tren', 'Bicicleta'], 'answer' => 1],
            ['q' => '¿Qué usamos para protegernos de la lluvia además del paraguas?', 'options' => ['Anteojos', 'Impermeable', 'Guantes', 'Bufanda'], 'answer' => 1],
            ['q' => '¿Qué animal tiene la trompa larga y colmillos?', 'options' => ['Rinoceronte', 'Elefante', 'Hipopótamo', 'Jabalí'], 'answer' => 1],
            ['q' => '¿Cuánto es 3 x 3?', 'options' => ['6', '9', '12', '3'], 'answer' => 1],
        ],
    ],

    // ------------------------------------------------------------ Tutti Frutti / ¡Basta!
    'tuttifrutti' => [
        'rounds' => 4,
        'round_seconds' => 90,
        'validate_seconds' => 35,   // tiempo para revisar/validar las respuestas
        'reveal_seconds' => 9,
        'categories' => ['Nombre', 'Apellido', 'País o ciudad', 'Animal', 'Fruta o verdura', 'Color', 'Objeto', 'Marca'],
        'letters' => ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'V'],
    ],

    // ------------------------------------------------------------ Memoria (memotest)
    'memoria' => [
        'rounds' => 1,
        'round_seconds' => 400,
        'pairs' => 18,           // 18 pares = 36 cartas (6x6)
        'flip_ms' => 1500,       // cuánto quedan visibles las cartas que no coinciden
        'faces' => [
            '🐶', '🐱', '🦊', '🐸', '🐼', '🦁', '🐵', '🐷', '🐧', '🐙', '🦄', '🐝',
            '🦋', '🐢', '🐠', '🌟', '🍕', '🍦', '⚽', '🚀', '🎈', '🎸', '🌈', '🍩',
        ],
    ],

    // ------------------------------------------------------------ Ahorcado
    'hangman' => [
        'rounds' => 5,
        'round_seconds' => 100,
        'max_misses' => 6,   // partes del muñeco (cabeza, cuerpo, 2 brazos, 2 piernas)
        // Palabras sin tildes (para el teclado); se comparan en minúscula (ñ incluida).
        // Agrupadas por categoría: la categoría se muestra como PISTA.
        'words' => [
            'Animal' => ['perro', 'gato', 'elefante', 'jirafa', 'tortuga', 'caballo', 'delfin', 'mariposa', 'araña', 'pulpo', 'ballena', 'abeja', 'zorro', 'lobo', 'gallina', 'serpiente', 'cangrejo', 'pinguino', 'tigre', 'leon'],
            'Comida' => ['pizza', 'helado', 'banana', 'hamburguesa', 'sandia', 'zanahoria', 'empanada', 'manzana', 'naranja', 'chocolate', 'queso', 'fideos', 'galleta', 'durazno'],
            'Objeto' => ['guitarra', 'piano', 'telefono', 'televisor', 'ventana', 'puerta', 'escoba', 'reloj', 'lampara', 'martillo', 'paraguas', 'mochila', 'tijera'],
            'Lugar' => ['escuela', 'playa', 'montaña', 'castillo', 'hospital', 'iglesia', 'estadio', 'museo', 'biblioteca', 'aeropuerto'],
            'Naturaleza' => ['arbol', 'flor', 'girasol', 'estrella', 'planeta', 'volcan', 'cascada', 'nube', 'rio'],
            'Transporte' => ['auto', 'camion', 'avion', 'barco', 'tren', 'moto', 'cohete', 'bicicleta', 'submarino', 'helicoptero'],
            'Profesion' => ['bombero', 'medico', 'policia', 'cartero', 'cocinero', 'maestro', 'piloto', 'pintor', 'carpintero', 'jardinero'],
            'Pais' => ['argentina', 'brasil', 'chile', 'uruguay', 'peru', 'colombia', 'mexico', 'españa', 'francia', 'italia', 'japon', 'canada', 'egipto', 'portugal', 'alemania'],
            'Ciudad' => ['madrid', 'barcelona', 'roma', 'paris', 'londres', 'tokio', 'lima', 'bogota', 'santiago', 'miami', 'berlin', 'moscu'],
            'Color' => ['rojo', 'azul', 'verde', 'amarillo', 'violeta', 'rosa', 'marron', 'negro', 'blanco', 'gris', 'celeste'],
            'Deporte' => ['futbol', 'basquet', 'tenis', 'voley', 'natacion', 'boxeo', 'ciclismo', 'golf', 'rugby', 'hockey', 'atletismo', 'esqui'],
        ],
    ],

    // ------------------------------------------------------------ Moderación del chat
    // Cantidad de avisos por lenguaje ofensivo antes de expulsar. Si el usuario
    // reincide después de haber sido expulsado, se bloquea su IP en esa sala.
    'profanity_warnings' => 3,

    // Groserías/insultos a filtrar en el chat. Se comparan sin tildes, en minúscula
    // y por palabra completa (o "pegadas", para evasiones tipo "p u t o"). Es editable.
    'profanity' => [
        'puta', 'puto', 'putas', 'putos', 'puton', 'putazo', 'putamadre', 'reputa', 'reputamadre',
        'hijodeputa', 'hijadeputa', 'hdp', 'lpm', 'ctm', 'qlo',
        'mierda', 'mierdas', 'mierdero',
        'concha', 'conchudo', 'conchuda', 'conchatumadre', 'conchetumadre',
        'pelotudo', 'pelotuda', 'pelotudos', 'pelotudas',
        'forro', 'forra', 'forros', 'forras',
        'carajo', 'cagar', 'cagada', 'cagadas', 'cagon', 'cagona', 'cagones', 'cagaste', 'cagando', 'cagate', 'cagador',
        'verga', 'vergas', 'vergazo',
        'pija', 'pijas', 'pijudo',
        'culo', 'culero', 'culiado', 'culiao', 'culeado', 'culeao',
        'coger', 'cojer', 'cogida',
        'joder', 'jodete', 'jodido', 'jodida',
        'cabron', 'cabrona', 'cabrones', 'cabronazo',
        'gilipollas', 'gilipollez',
        'maricon', 'maricona', 'marica', 'maricones',
        'trolo', 'trola', 'trolos', 'trolas',
        'pendejo', 'pendeja', 'pendejos', 'pendejas', 'pendejada',
        'zorra', 'zorras',
        'imbecil', 'imbeciles', 'estupido', 'estupida', 'idiota', 'idiotas',
        'tarado', 'tarada', 'subnormal', 'retrasado', 'mogolico', 'mongolico',
        'polla', 'pollas', 'cojones', 'gonorrea',
        'malparido', 'malparida', 'chinga', 'chingada', 'chingar', 'chingas', 'pinche',
    ],
];
