<?php

/**
 * Catálogo de deportes soportados por FIFARDOS.
 *
 * Cada deporte define:
 *   - name             : nombre mostrado
 *   - icon             : emoji / identificador para la UI
 *   - type             : 'individual' (1 jugador vs 1 jugador) | 'team' (equipo vs equipo)
 *   - players_per_side : jugadores que componen cada lado (para equipos)
 *   - scoring          : 'goals' (más goles gana) | 'points' (más puntos gana) | 'sets' (más sets gana)
 *   - allows_draw      : permite empate en el marcador principal
 *   - max_sets         : (solo sets) máximo de sets jugados
 *   - points           : sistema de puntaje para la tabla de posiciones
 *   - minutes          : duración estimada de un partido
 */
return [
    'fifa' => [
        'name' => 'Videojuego / Consola',
        'icon' => '🎮',
        'type' => 'individual',
        'players_per_side' => 1,
        'scoring' => 'goals',
        'allows_draw' => true,
        'points' => ['win' => 3, 'draw' => 1, 'loss' => 0],
        'minutes' => 6,
        'uses_penalties' => true,
    ],
    'soccer' => [
        'name' => 'Fútbol 11',
        'icon' => '⚽',
        'type' => 'team',
        'players_per_side' => 11,
        'scoring' => 'goals',
        'allows_draw' => true,
        'points' => ['win' => 3, 'draw' => 1, 'loss' => 0],
        'minutes' => 90,
        'uses_penalties' => true,
    ],
    'futsal' => [
        'name' => 'Fútbol 5 / Futsal',
        'icon' => '🥅',
        'type' => 'team',
        'players_per_side' => 5,
        'scoring' => 'goals',
        'allows_draw' => true,
        'points' => ['win' => 3, 'draw' => 1, 'loss' => 0],
        'minutes' => 40,
        'uses_penalties' => true,
    ],
    'football6' => [
        'name' => 'Fútbol 6',
        'icon' => '⚽',
        'type' => 'team',
        'players_per_side' => 6,
        'scoring' => 'goals',
        'allows_draw' => true,
        'points' => ['win' => 3, 'draw' => 1, 'loss' => 0],
        'minutes' => 30,
        'uses_penalties' => true,
    ],
    'football7' => [
        'name' => 'Fútbol 7',
        'icon' => '⚽',
        'type' => 'team',
        'players_per_side' => 7,
        'scoring' => 'goals',
        'allows_draw' => true,
        'points' => ['win' => 3, 'draw' => 1, 'loss' => 0],
        'minutes' => 30,
        'uses_penalties' => true,
    ],
    'football8' => [
        'name' => 'Fútbol 8',
        'icon' => '⚽',
        'type' => 'team',
        'players_per_side' => 8,
        'scoring' => 'goals',
        'allows_draw' => true,
        'points' => ['win' => 3, 'draw' => 1, 'loss' => 0],
        'minutes' => 40,
        'uses_penalties' => true,
    ],
    'basketball' => [
        'name' => 'Básquet 5x5',
        'icon' => '🏀',
        'type' => 'team',
        'players_per_side' => 5,
        'scoring' => 'points',
        'allows_draw' => true,
        'points' => ['win' => 2, 'draw' => 1, 'loss' => 0],
        'minutes' => 40,
        'uses_penalties' => false,
    ],
    'basketball3' => [
        'name' => 'Básquet 3x3',
        'icon' => '🏀',
        'type' => 'team',
        'players_per_side' => 3,
        'scoring' => 'points',
        'allows_draw' => true,
        'points' => ['win' => 2, 'draw' => 1, 'loss' => 0],
        'minutes' => 20,
        'uses_penalties' => false,
    ],
    'volleyball' => [
        'name' => 'Vóley',
        'icon' => '🏐',
        'type' => 'team',
        'players_per_side' => 6,
        'scoring' => 'sets',
        'allows_draw' => false,
        'max_sets' => 5,
        'points' => ['win' => 2, 'draw' => 1, 'loss' => 0],
        'minutes' => 60,
        'uses_penalties' => false,
    ],
    'tennis' => [
        'name' => 'Tenis',
        'icon' => '🎾',
        'type' => 'individual',
        'players_per_side' => 1,
        'scoring' => 'sets',
        'allows_draw' => false,
        'max_sets' => 3,
        'points' => ['win' => 2, 'draw' => 1, 'loss' => 0],
        'minutes' => 90,
        'uses_penalties' => false,
    ],
    'padel' => [
        'name' => 'Pádel',
        'icon' => '🏓',
        'type' => 'team',
        'players_per_side' => 2,
        'scoring' => 'sets',
        'allows_draw' => false,
        'max_sets' => 3,
        'points' => ['win' => 2, 'draw' => 1, 'loss' => 0],
        'minutes' => 60,
        'uses_penalties' => false,
    ],
    'table_tennis' => [
        'name' => 'Tenis de mesa',
        'icon' => '🏓',
        'type' => 'individual',
        'players_per_side' => 1,
        'scoring' => 'sets',
        'allows_draw' => false,
        'max_sets' => 5,
        'points' => ['win' => 2, 'draw' => 1, 'loss' => 0],
        'minutes' => 30,
        'uses_penalties' => false,
    ],
    'pickleball' => [
        'name' => 'Pickleball',
        'icon' => '🏸',
        'type' => 'team',
        'players_per_side' => 2,
        'scoring' => 'sets',
        'allows_draw' => false,
        'max_sets' => 3,
        'points' => ['win' => 2, 'draw' => 1, 'loss' => 0],
        'minutes' => 40,
        'uses_penalties' => false,
    ],
    'handball' => [
        'name' => 'Handball',
        'icon' => '🤾',
        'type' => 'team',
        'players_per_side' => 7,
        'scoring' => 'goals',
        'allows_draw' => true,
        'points' => ['win' => 2, 'draw' => 1, 'loss' => 0],
        'minutes' => 60,
        'uses_penalties' => false,
    ],
    'rugby' => [
        'name' => 'Rugby',
        'icon' => '🏉',
        'type' => 'team',
        'players_per_side' => 15,
        'scoring' => 'points',
        'allows_draw' => true,
        'points' => ['win' => 4, 'draw' => 2, 'loss' => 0],
        'minutes' => 80,
        'uses_penalties' => false,
    ],
];
